<a href="https://colab.research.google.com/github/201906163-bakjunha/Aipython/blob/main/240503_aipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = list(map(int, input().split()))

if sum(a) > 100:
  if a[0] > 40 and [1] >40:
    print('Pass')
  elif a[0] < 40:
    print('ENG FAIL')


In [ ]:
num = input()
num_list = list(num)
aa = map(int, num_list)
print(sum(aa))


12345
['1', '2', '3', '4', '5']


In [ ]:
#다음 리스트에서 확장자가 png나 jpg인 파일의 확장자를 출력하는 파이썬 코드를 작성하세요


In [25]:
import numpy as np
q1 =np.arange(1, 10, 2)
q2= np.ones((3,4))
q3=np.linspace(0, 1, 10)

print(q1)
print(q2)
print(q3)
print(f'{q1}\n{q2}\n{q3}' )

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [29]:
#a행렬 생성
a=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
#a의 모얄 출력
print(a.shape)
#19의 값 추출
print(a[3,3])
#슬라이싱을 이용1,2,6,7 추출
print(a[:2,:2])
#,,19,20,24,25 추출
print(a[:-2,:-2])
#0축 첫 번째, 두 번째 행렬 추출
print(a[0:2], axis=0)

#1축 마지막 열, 마지막 직전 열 추출

(5, 5)
19
[[1 2]
 [6 7]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


TypeError: 'axis' is an invalid keyword argument for print()

In [33]:
#b=np.arange(1,37)
b=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10,11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]], [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]])
print(b.shape, b.size)
print(b.reshape(3,4,3))
print(b.flatten())

(3, 3, 4) 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [30]:
a=list(range(13,37))
print(a)

[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
